<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
$_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/product');
$image_width = (isset($_config['ratio_width']) && $_config['ratio_width'])?$_config['ratio_width']:800;
$image_height = (isset($_config['ratio_height']) && $_config['ratio_height'])?$_config['ratio_height']:800;
$thumb_width = 75;
$aspect_ratio = (isset($_config['aspect_ratio']))?$_config['aspect_ratio']:0;
$thumb_height = 75 * $image_height / $image_width;
if (!$aspect_ratio)
    $thumb_height = 75;
?>



<?php
$product = $this->getProduct();
$shotDesc=$product->getShortDescription();
$images = $product->getMediaGalleryImages();

$producSmallImageUrl = $block->getUrl('pub/media/catalog').'product'.$product->getSmallImage();
?>
<?php
$this->_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $swatchHelper=$this->_objectManager->get("Magento\Swatches\Helper\Media");
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
// brand logo is my Visual Swatch attribute 
$ma1_optionIdvalue=$product->getData('machine_wash_30_icon'); 
$swatchCollection->addFieldtoFilter('option_id',$ma1_optionIdvalue);
$ma1_item=$swatchCollection->getFirstItem();
$ma1=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma1_item->getValue());

// iron_low Visual Swatch attribute 
$ma2_optionIdvalue=$product->getData('iron_low'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma2_optionIdvalue);
$ma2_item=$swatchCollection->getFirstItem();
$ma2=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma2_item->getValue());


// iron_low Visual Swatch attribute 
$ma3_optionIdvalue=$product->getData('dry_clean_icon'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma3_optionIdvalue);
$ma3_item=$swatchCollection->getFirstItem();
$ma3=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma3_item->getValue());

// iron_low Visual Swatch attribute 
$ma4_optionIdvalue=$product->getData('machine_wash_40'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma4_optionIdvalue);
$ma4_item=$swatchCollection->getFirstItem();
$ma4=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma4_item->getValue());


// iron_low Visual Swatch attribute 
$ma5_optionIdvalue=$product->getData('do_not_bleech_icon'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma5_optionIdvalue);
$ma5_item=$swatchCollection->getFirstItem();
$ma5=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma5_item->getValue());


// iron_low Visual Swatch attribute 
$ma6_optionIdvalue=$product->getData('do_not_iron_icon'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma6_optionIdvalue);
$ma6_item=$swatchCollection->getFirstItem();
$ma6=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma6_item->getValue());


// iron_low Visual Swatch attribute 
$ma7_optionIdvalue=$product->getData('do_not_tumble_dry_icon'); 
$swatchCollection = $this->_objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
$swatchCollection->addFieldtoFilter('option_id',$ma7_optionIdvalue);
$ma7_item=$swatchCollection->getFirstItem();
$ma7=$swatchHelper->getSwatchAttributeImage('swatch_thumb', $ma7_item->getValue());
//var_dump($ma1_optionIdvalue);
//var_dump(strpos($ma1,"."));



$j=0;
echo '<div class="imag-main">';
foreach ($images as $image) {
 // echo "<pre>";
 // print_r($image->getUrl());die;
$class='imag'.$j;
if($j==1){
    echo '<li ><img id="largeImage" src="'.$producSmallImageUrl.'"/><p>'.$shotDesc.'</p>

    </li>';
}
$j++;
}
echo "</div>";

$j=0;
echo '<div class="imag"><ul class="imggal">';
foreach ($images as $image) {
 // echo "<pre>";
 // print_r($image->getUrl());die;
$class='imag'.$j;

    echo '<li ><img id="test-'.$j.'" src="'.$image->getUrl().'" title="" /></li>';


$j++;
}
echo "</ul></div>";
?>



<?php
echo $this->getChildHtml('catalog.product.related1');
?>

<script type="text/javascript">
    require([
    'jquery',
    'jquery/ui'
], function ($) {
            jQuery('#sidebar').stickySidebar({
                sidebarTopMargin: 20,
                footerThreshold: 100
            });
});
  jQuery(window).on( 'scroll', function(){
    console.log('Event Fired');
    jQuery('#sidebar').addClass('sticky');
  });
</script>


<div class="mobilegallary">
  <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <!-- <div class="loader">
            <img src="<?php /* @escapeNotVerified */ //echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ //echo __('Loading...') ?>">
        </div> -->
    </div>
</div> 
<!-- <script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                    "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                    "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                    "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                    "width": <?php /* @escapeNotVerified */ echo $image_width; ?>,
                    "thumbwidth": <?php /* @escapeNotVerified */ echo $thumb_width; ?>,
                    "thumbheight": <?php /* @escapeNotVerified */ echo $thumb_height; ?>,
                    <?php if(!$aspect_ratio): ?>
                    "height": <?php /* @escapeNotVerified */ echo $image_height; ?>,
                    <?php endif; ?>
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                    "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>"
                },
                "fullscreen": {
                    "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                    "arrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/caption"); ?>,
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                },
                "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
            }
        }
    }
</script>
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    var loaded = false;
    $('.product.media .gallery-placeholder').bind("DOMSubtreeModified",function(){
        $('.product.media .fotorama').on('fotorama:ready', function (e, fotorama, extra) {
            //console.log('fotorama is loaded');
            loaded = false;
            $('.product.media .fotorama').on('fotorama:load', function (e, fotorama, extra) {
                if(!loaded){
                    $('.product.media .fotorama__stage .fotorama__loaded--img').trigger('zoom.destroy');
                    $('.product.media .fotorama__stage .fotorama__active').zoom({
                        touch:false
                    });
                    loaded = true;
                }
            });
            $('.product.media .fotorama').off('fotorama:showend').on('fotorama:showend', function (e, fotorama, extra) {
                $('.product.media .fotorama__stage .fotorama__loaded--img').trigger('zoom.destroy');
                $('.product.media .fotorama__stage .fotorama__active').zoom({
                    touch:false
                });
            });
            $('.fotorama').off('fotorama:fullscreenenter').on('fotorama:fullscreenenter', function (e, fotorama, extra) {
                $('.product.media .fotorama__stage .fotorama__loaded--img').trigger('zoom.destroy');
                $('img.zoomImg').remove();
            });
            $('.fotorama').off('fotorama:fullscreenexit').on('fotorama:fullscreenexit', function (e, fotorama, extra) {
                $('.product.media .fotorama__stage .fotorama__loaded--img').trigger('zoom.destroy');
                $('img.zoomImg').remove();
                $('img.fotorama__img').not('.fotorama__img--full').each(function(){
                    $(this).after($(this).parent().children("img.fotorama__img--full"));
                });
                $('.product.media .fotorama__stage .fotorama__active').zoom({
                    touch:false
                });
                $('.product.media .fotorama').off('fotorama:showend').on('fotorama:showend', function (e, fotorama, extra) {
                    $('.product.media .fotorama__stage .fotorama__loaded--img').trigger('zoom.destroy');
                    $('.product.media .fotorama__stage .fotorama__active').zoom({
                        touch:false
                    });
                });
            });
        });
    });
});
</script> -->

</div>
<script type="text/javascript">
jQuery('[id^="test-"]').click(function(){
    //alert(this.id);
    jQuery('#largeImage').attr('src',jQuery(this).attr('src').replace('test','large'));
    //$('#description').html($(this).attr('alt'));
});
</script>

