<?php
    $header_type = $this->getConfig('porto_settings/header/header_type');
    $show_ticker = $this->getConfig('porto_settings/header/show_ticker');
?>
<header class="page-header type<?php echo $header_type; ?>">
<?php echo $this->getChildHtml("header_customer_form_login"); ?>
<?php if($header_type == 3 || $header_type == 14 || $header_type == 9): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
				  <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("header.links"); ?>
				<?php echo $this->getChildHtml("custom_block"); ?>


            </div>

            <div class="bottom-panel">

          
            </div>
        </div>
    </div>

    <!--ticker added here -->


<div class="row tickheader" style="background-color: #000; color: #fff; border: 0; text-align: center; padding: 15px 0 !important;">
<div class="col-md-12">
<div class="text-area">
<div class="ticker">
<ul>
<li>
<div id="t70403" class="t70403-pos"><span class="t70403-discount">10%</span> off your first order<span class="t70403-pipe">|</span> Code: <span class="t70403-code">f10gff</span> <span class="t70403-pipe">|</span> <span class="t70403-conditions">Valid on full-price items only</span><span class="t70403-expand"></span></div>
</li>
<li>
<div id="t70404" class="t70404-pos"><span class="t70404-discount">20%</span> off your second order<span class="t70404-pipe">|</span> Code: <span class="t70404-code">f10gff</span> <span class="t70404-pipe">|</span> <span class="t70404-conditions">Valid on full-price items only</span><span class="t70404-expand"></span></div>
</li>
</ul>
</div>
</div>
</div>
</div>


<!-- ticker end here -->

<?php elseif($header_type == 12): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <div class="top-links-area">
                    <a class="top-links-icon" href="javascript:void(0)">links</a>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <?php echo $this->getChildHtml("minilogin"); ?>
                <?php echo $this->getChildHtml("custom_block"); ?>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 13): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <div class="menu-area">
                    <a href="javascript:void(0)" class="shop-menu">Shop</a>
                    <?php echo $this->getChildHtml("navigation.sections"); ?>
                </div>
                <div class="top-links-area">
                    <a class="top-links-icon" href="javascript:void(0)">links</a>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
                <?php echo $this->getChildHtml("minilogin"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 5 ): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minilogin"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <div class="search-area">
            <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 6 ): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <div class="search-area">
            <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("minilogin"); ?>
        <?php echo $this->getChildHtml("custom_block"); ?>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 7 ): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("minicart"); ?>
            <span class="split"></span>
            <div class="toplinks-area">
                <a href="javascript:void(0)" class="toplinks-toggle"><?php echo __('Links'); ?></a>
                <?php echo $this->getChildHtml("header.links"); ?>
            </div>
            <span class="split"></span>
            <?php echo $this->getChildHtml("minilogin"); ?>
            <?php echo $this->getChildHtml("custom_block"); ?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="switcher-area">
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
        </div>
         <div class="search-area">
            <a href="javascript:void(0)" class="search-toggle-icon"><em class="porto-icon-search"></em><?php echo __('Search'); ?></a>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
    </div>
<?php elseif($header_type == 8 ): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("minicart"); ?>
    <?php echo $this->getChildHtml("top.search"); ?>
    <?php echo $this->getChildHtml("minilogin"); ?>
    <?php echo $this->getChildHtml("custom_block"); ?>
    </div>
    <div class="menu-container">
        <?php
            $toggle_text = $this->getConfig('porto_settings/header/toggle_text');
            $custom_block_id_8 = $this->getConfig('porto_settings/header/static_block_8');
        ?>
        <div class="container">
            <div class="menu-wrapper row">
                <div class="drop-menu">
                    <a href="javascript:void(0)">
                        <?php echo $toggle_text; ?>
                    </a>
                    <?php echo $this->getChildHtml("navigation.sections"); ?>
                </div>
                <div class="custom-menu-block">
                <?php
                    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                    if($block) {
                        $block->setBlockId($custom_block_id_8);
                    }
                    if($block){
                        echo $block->toHtml();
                    }
                ?>
                </div>
            </div>
        </div>
    </div>
<?php elseif($header_type == 10 ): ?>
    <div class="switcher-area">
        <?php echo $this->getChildHtml("skip_to_content"); ?>
        <?php echo $this->getChildHtml("currency"); ?>
        <?php echo $this->getChildHtml("store_language"); ?>
        <?php echo $this->getChildHtml("minilogin"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
    </div>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
    <?php echo $this->getChildHtml("top.search"); ?>
    </div>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="custom-block-area">
        <?php echo $this->getChildHtml("custom_block"); ?>
    </div>
<?php else: ?>

 
    <div class="header content">

    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
    <?php echo $this->getChildHtml("top.search"); ?>
        
    <?php //echo $this->getChildHtml("minilogin"); ?>
    <?php //echo $this->getChildHtml("custom_block"); ?>
    </div>
     <div class="login-content clearfix" id="login-content">
        <div class="login-content_iner">
         <div class="login-content_left">
            <div class="block block-new-customer">
                <div class="block-title">
                    <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Customers') ?></strong>
                </div>
                <div class="block-content" aria-labelledby="block-new-customer-heading">
                    <p><?php /* @escapeNotVerified */ echo __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?></p>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <a href="<?php /* @escapeNotVerified */ echo $this->getUrl('customer/account/create') ?>" class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
                        </div>
                    </div>
                </div>
            </div>
              
            </div>
            
            <div class="login-content_right">
            <?php echo $this->getLayout()
                  ->createBlock('Magento\Customer\Block\Form\Login')
                  ->setTemplate('VS_Template::html/login.phtml')
                  ->toHtml(); ?>
            </div>
        </div>
     </div>   
    
<?php endif; ?>
</header>


<script type="text/javascript">
       require([
            'jquery',
            'jquery/ui'
        ], function ($) {
           <?php if($show_ticker): ?> 
               if (jQuery(".ticker").length > 0) {
                    jQuery('.ticker').ticker();
                }
            <?php else: ?>
                jQuery('.ticker').hide();
            <?php endif; ?>

            jQuery('#login-dropdown').click(function(){
                jQuery(this).toggleClass('active');
                jQuery('#login-content').toggleClass('active');
            });

        });
  
</script>