<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php
$_helper = $this->helper('Smartwave\Porto\Helper\Data');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol = $objectManager->get('\Magento\Directory\Block\Currency');
$currencyManager = $objectManager->create('Magento\Directory\Model\PriceCurrency');
$currencies = $currencysymbol->getCurrencies();
?>

<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
        <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
                <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>
                        <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($block->escapeHtml($block->getCurrentStoreCode())).'.png'; ?>" />
                    <?php endif; ?>
                    <span><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
            data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
            "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null}}'>
            <div  id="closearea"  class="closesearch closesearchnew"><a class="closesearchwindow" href="javascript:void(0)">x</a></div>
            <?php foreach ($block->getStores() as $_lang):
            ?>

            
            <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>                
                <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                       
                       <div class="imageblock">
                        <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>                        
                            <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" /> 
                        <?php endif; ?>
                    </div></a>
                    


                    <div class="currencyblog"> 
                        <?php  echo isset($currencies[$_lang->getCurrentCurrencyCode()])?$currencies[$_lang->getCurrentCurrencyCode()]:'';  ?>
                        (
                        <?php echo $currencySymbol = $currencyManager->getCurrencySymbol(null,$_lang->getCurrentCurrencyCode());?>  )          
                        <span> <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'><?php echo $block->escapeHtml($_lang->getName()) ?></a></span>

                    </div>

                </li>
            <?php else:?>
                <li class="selectedCur switcher-option" style="display:none">
                    <div class="currencyblog">         
                        <span> <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'></a></span>

                    </div>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- <div class="closesearch closesearchnew"><a class="closesearchwindow" href="javascript:void(0)">x</a></div> -->
    </ul>

</div>
</div>
<?php endif; ?>

